name: recipeapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #State Managment
  mobx: ^2.1.3

  #MobX's Widgets
  flutter_mobx: ^2.0.6+5 

  #Mobx's annotations
  mobx_codegen: ^2.1.1

  #Json Converter
  json_serializable: ^6.5.4

  #Json Annotations
  json_annotation: ^4.7.0

  #Equatable Converter
  freezed: ^2.2.1 
  
  #Freezed Annotations
  freezed_annotation: ^2.2.0 

  #Dependecy Injection 
  get_it: ^7.2.0 

  #Dependency Injection Annotations
  injectable: ^2.0.1

  #Navigator
  go_router: ^6.5.0

  #Network
  dio: ^5.0.3

  #Hide Keys
  flutter_dotenv: ^5.0.2

  #Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #Encryption Local Database
  flutter_secure_storage: ^8.0.0

  #Theme
  flex_color_scheme: ^6.1.1

  #Icons
  font_awesome_flutter: ^10.2.1
  
  #Text Theme
  google_fonts: ^4.0.3
  #cupertino_icons: ^1.0.2

  #Persistant Bottom Navigation Bar
  persistent_bottom_nav_bar: ^5.0.2

  #ViewState Loading
  flutter_easyloading: ^3.0.5

  #Error Handling
  either_dart: ^0.3.0

  #Refresh Indicator
  pull_to_refresh: ^2.0.0

  #Shimmer
  shimmer: ^2.0.0

  #Share
  share_plus: ^6.3.1

  #Widget Extensions
  flutter_slidable: ^2.0.0
  group_button: ^5.2.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  #Generators
  build_runner: ^2.3.3
  injectable_generator: ^2.0.1
  hive_generator: ^2.0.0

  #Lints
  flutter_lints: ^2.0.1
  
flutter:
  uses-material-design: true

  assets:
    - assets/.env

scripts:
  build_runner_delete_conflict: flutter pub run build_runner build --delete-conflicting-outputs
  build_runner_build: flutter pub run build_runner build